spring.application.name=Caache_Impl

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Redis config - Ubuntu(WSL) wala .. first need to start the redis service from wsl..

#spring.data.redis.host=localhost
#spring.data.redis.port=6379



# for cloud.redis.ai --> redis insight desktop app (credential is available on https://cloud.redis.io/  public endpoint and password secction)
spring.data.redis.host=redis-17515.crce179.ap-south-1-1.ec2.cloud.redislabs.com
spring.data.redis.port=17515
spring.data.redis.password=AvTYb1Hn8ZzHNRtzNyiqc6zSvTxKcLv9

