spring.application.name=Caache_Impl

spring.datasource.url=jdbc:mysql://localhost:3306/employee_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Redis config - Ubuntu(WSL) wala .. first need to start the redis service
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

# for cloud.redis.ai
#spring.data.redis.host=redis-16260.c212.ap-south-1-1.ec2.cloud.redislabs.com
#spring.data.redis.port=16260
#spring.data.redis.password=HIVMUHMaZQP1jnesYnd5ufIWhji4C4BO

